### ISSUE TITLE
`padelpy` implements similar functionality

### ISSUE THREAD

**Issue by JacksonBurns** [OlivierBeq/PaDEL_pywrapper#1]
I just wanted to make sure you are aware that [`padelpy`](https://github.com/ecrl/padelpy) exists and provides an interface to PaDEL-Descriptor from python. Found your work while looking for it, wanted to make sure you didn't accidentally reinvent the wheel.

**Comment by OlivierBeq** [comment]
Indeed, but having padelpy calculate other fingerprints than the PubChem fingerprints is rather tedious.
This was the driving force of this implementation (alongside the direct interaction with the java runtime).
